// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	problem "github.com/solitudealma/SOJ/backend/app/problem/cmd/api/internal/handler/problem"
	"github.com/solitudealma/SOJ/backend/app/problem/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/problem",
				Handler: problem.GetProblemListInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/problem/:problemId",
				Handler: problem.GetProblemInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
