// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Id       int64  `json:"userId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type RegisterReq struct {
	Username          string `json:"username" validate:"required,lte=16,gte=4"`
	Password          string `json:"password" validate:"required,gte=6,lte=20"`
	PasswordConfirmed string `json:"passwordConfirmed" validate:"required,eqfield=Password"`
}

type RegisterResp struct {
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"userInfo"`
}

type LogoutReq struct {
	Token string `header:"token" validate:"required"`
}

type LogoutResp struct {
}

type GetUserInfoReq struct {
	Token string `header:"token" validate:"required"`
}

type GetUserInfoResp struct {
	UserInfo UserInfo `json:"userInfo"`
}

type UpdateUserInfoReq struct {
	Username string `json:"username" validate:"required"`
}

type UpdateUserInfoResp struct {
}
