// Code generated by goctl. DO NOT EDIT.
// Source: judge.proto

package server

import (
	"context"

	"github.com/solitudealma/SOJ/backend/app/judge/cmd/rpc/internal/logic"
	"github.com/solitudealma/SOJ/backend/app/judge/cmd/rpc/internal/svc"
	"github.com/solitudealma/SOJ/backend/app/judge/cmd/rpc/pb"
)

type JudgeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedJudgeServer
}

func NewJudgeServer(svcCtx *svc.ServiceContext) *JudgeServer {
	return &JudgeServer{
		svcCtx: svcCtx,
	}
}

func (s *JudgeServer) Compile(ctx context.Context, in *pb.CompileReq) (*pb.CompileResp, error) {
	l := logic.NewCompileLogic(ctx, s.svcCtx)
	return l.Compile(in)
}

func (s *JudgeServer) Exce(ctx context.Context, in *pb.ExceReq) (*pb.ExceResp, error) {
	l := logic.NewExceLogic(ctx, s.svcCtx)
	return l.Exce(in)
}
