// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	solution "github.com/solitudealma/SOJ/backend/app/solution/cmd/api/internal/handler/solution"
	"github.com/solitudealma/SOJ/backend/app/solution/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/solution",
				Handler: solution.GetSolutionListInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/solution/:solutionId",
				Handler: solution.GetSolutionInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/solution/saved/:authorId",
					Handler: solution.GetSavedSolutionInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/solution",
					Handler: solution.CreateSolutionInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
