// Code generated by goctl. DO NOT EDIT.
package types

type Solution struct {
	Title             string `json:"title"`
	CreateTime        int64  `json:"createTime"`
	UpdateTime        int64  `json:"updateTime"`
	SolutionId        int64  `json:"solutionId"`
	ProblemId         string `json:"problemId"`
	ProblemSource     string `json:"problemSource"`
	AuthorId          int64  `json:"authorId"`
	AuthorName        string `json:"authorName"`
	AuthorAvatar      string `json:"authorAvatar"`
	ProblemDifficulty int64  `json:"problemDifficulty"`
	Read              int64  `json:"read"`
}

type SolutionInfo struct {
	ProblemId         string `json:"problemId"`
	Title             string `json:"title"`
	ProblemSource     string `json:"problemSource"`
	Content           string `json:"content"`
	ProblemLink       string `json:"problemLink"`
	ProblemDifficulty int64  `json:"problemDifficulty"`
	UpdateTime        int64  `json:"updateTime"`
	AuthorId          int64  `json:"authorId"`
	AuthorName        string `json:"authorName"`
	AuthorAvatar      string `json:"authorAvatar"`
	Read              int64  `json:"read"`
}

type GetSolutionListInfoReq struct {
	CurrentPage int `form:"currentPage" validate:"required,gte=1"`
}

type GetSolutionListInfoResp struct {
	Current   int        `json:"current"`
	Total     int64      `json:"total"`
	Solutions []Solution `json:"solutions"`
}

type GetSolutionInfoReq struct {
	SolutionId int64 `path:"solutionId" validate:"required"`
}

type GetSolutionInfoResp struct {
	SolutionInfo SolutionInfo `json:"solutionInfo"`
}

type GetSavedSolutionInfoReq struct {
	AuthorId int64 `path:"authorId" validate:"required"`
}

type GetSavedSolutionInfoResp struct {
	ProblemId         string `json:"problemId"`
	Title             string `json:"title"`
	ProblemSource     string `json:"problemSource"`
	Content           string `json:"content"`
	ProblemLink       string `json:"problemLink"`
	ProblemDifficulty int64  `json:"problemDifficulty"`
}

type CreateSolutionInfoReq struct {
	ProblemId         string `json:"problemId" validate:"required"`
	Title             string `json:"title" validate:"required"`
	ProblemSource     string `json:"problemSource" validate:"required"`
	Content           string `json:"content"`
	ProblemLink       string `json:"problemLink" validate:"required"`
	ProblemDifficulty int64  `json:"problemDifficulty" validate:"required"`
	AuthorId          int64  `json:"authorId" validate:"required"`
	AuthorName        string `json:"authorName" validate:"required"`
	AuthorAvatar      string `json:"authorAvatar" validate:"required"`
	Type              int64  `json:"type" validate:"oneof=0 1"`
}

type CreateSolutionInfoResp struct {
	SolutionId int64 `json:"solutionId"`
}
