// Code generated by goctl. DO NOT EDIT.
package types

type Solution struct {
	Title             string `json:"title"`
	CreateTime        int64  `json:"createTime"`
	SolutionId        int64  `json:"solutionId"`
	ProblemId         string `json:"problemId"`
	ProblemSource     string `json:"problemSource"`
	AuthorId          int64  `json:"authorId"`
	AuthorName        string `json:"authorName"`
	AuthorAvatar      string `json:"authorAvatar"`
	ProblemDifficulty int64  `json:"problemDifficulty"`
	Read              int64  `json:"read"`
}

type SolutionInfo struct {
	ProblemId         string `json:"problemId"`
	Title             string `json:"title"`
	ProblemSource     string `json:"problemSource"`
	Content           string `json:"content"`
	ProblemLink       string `json:"problemLink"`
	ProblemDifficulty int64  `json:"problemDifficulty"`
	UpdateTime        int64  `json:"updateTime"`
	AuthorId          int64  `json:"authorId"`
	AuthorName        string `json:"authorName"`
	AuthorAvatar      string `json:"authorAvatar"`
	Read              int64  `json:"read"`
}

type GetSolutionListInfoReq struct {
	CurrentPage int `form:"currentPage" validate:"required,gte=1"`
}

type GetSolutionListInfoResp struct {
	Current   int        `json:"current"`
	Total     int64      `json:"total"`
	Solutions []Solution `json:"solutions"`
}

type GetSolutionInfoReq struct {
	SolutionId int64 `path:"solutionId" validate:"required"`
}

type GetSolutionInfoResp struct {
	SolutionInfo SolutionInfo `json:"solutionInfo"`
}
