// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type RegisterReq struct {
	Username          string `json:"username" validate:"required,lte=15,gte=0"`
	Password          string `json:"password" validate:"required,min=10"`
	PasswordConfirmed string `json:"passwordConfirmed" validate:"required,eqfield=Password"`
}

type RegisterResp struct {
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token string `json:"token"`
	User  User   `json:"userInfo"`
}

type UserInfoReq struct {
	Token string `header:"token" validate:"required"`
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
